/*
 * generated by Xtext
 */
package org.mondo.collaboration.security.macl.xtext.ui.contentassist

import org.mondo.collaboration.security.macl.xtext.ui.contentassist.AbstractAccessControlLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AccessControlLanguageProposalProvider extends AbstractAccessControlLanguageProposalProvider {
}
