/*
 * generated by Xtext
 */
package org.mondo.collaboration.security.mpbl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.mondo.collaboration.security.mpbl.xtext.ui.internal.MondoPropertyBasedLockingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MondoPropertyBasedLockingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MondoPropertyBasedLockingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MondoPropertyBasedLockingActivator.getInstance().getInjector(MondoPropertyBasedLockingActivator.ORG_MONDO_COLLABORATION_SECURITY_MPBL_XTEXT_MONDOPROPERTYBASEDLOCKING);
	}
	
}
